use std::collections::HashMap;
use std::fs::{self, File};
use std::io::Write;
use std::time::SystemTime;
use std::{fs::OpenOptions, path::PathBuf};

use deps::Dependencies;
use serde::{Deserialize, Serialize};
use xshell::{Shell, cmd};

mod android;
mod benchmarks;
mod build_metrics;
mod deps;

use android::AndroidLibrarySize;
use benchmarks::Benchmark;
use build_metrics::{Codesize, MetricCount};

type Result<T, E = Box<dyn std::error::Error>> = std::result::Result<T, E>;

mod flags {
    use std::path::PathBuf;

    xflags::xflags! {
        src "./src/main.rs"

        cmd run {
            /// The revset to pick. Passed on to `revset` to determine commits to examine.
            /// If unspecified, uses `HEAD^..HEAD` (only the latest commit).
            optional -r, --revset commit: String

            /// Repository URL to clone from
            required -u, --url url: String

            /// Repository path
            required -p, --path path: PathBuf

            /// Output file. Default: data.json
            optional -o, --output output: PathBuf

            /// List all available metrics
            optional --list-metrics

            /// Enable only the listed metrics (comma or space-separated)
            optional -m, --metrics metrics: String

            /// Merge remaining listed files into `output`. Does not run metric recorder.
            optional --merge

            repeated files: PathBuf
        }
    }
    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Run {
        pub files: Vec<PathBuf>,

        pub revset: Option<String>,
        pub url: String,
        pub path: PathBuf,
        pub output: Option<PathBuf>,
        pub list_metrics: bool,
        pub metrics: Option<String>,
        pub merge: bool,
    }

    impl Run {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}

fn main() -> Result<()> {
    let flags = match flags::Run::from_env() {
        Ok(flags) => flags,
        Err(err) => err.exit(),
    };

    if flags.merge {
        merge(flags)
    } else {
        run(flags)
    }
}

trait MetricRecorder {
    fn record(&self, sh: &Shell) -> Result<Vec<Metric>>;

    fn name(&self) -> &'static str;
    fn description(&self) -> &'static str;
}

fn run(flags: flags::Run) -> Result<()> {
    if !flags.files.is_empty() {
        return Err("no positional arguments accepted".into());
    }

    let sh = Shell::new()?;

    let repo = flags.path;

    let metric_recorders = &[
        &AndroidLibrarySize as &dyn MetricRecorder,
        &Codesize,
        &MetricCount,
        &Benchmark,
        &Dependencies::new("glean-core"),
        &Dependencies::new("glean"),
    ];

    if flags.list_metrics {
        for recorder in metric_recorders {
            println!("{}:\t{}", recorder.name(), recorder.description());
        }

        return Ok(());
    }

    let enabled_metrics = flags.metrics.unwrap_or_else(|| String::from(""));
    let enabled_metrics = enabled_metrics
        .split([' ', ','])
        .filter(|&s| s != "")
        .collect::<Vec<_>>();

    if repo.is_dir() {
        sh.change_dir(&repo);
        cmd!(sh, "git fetch origin").run()?;
    } else {
        let url = flags.url;
        cmd!(sh, "git clone {url} {repo} --branch main").run()?;
        sh.change_dir(&repo);
    }

    let revset = flags.revset.unwrap_or_else(|| String::from("HEAD^..HEAD"));
    let commits = cmd!(sh, "git rev-list {revset}").read()?;
    let commits = commits.lines().rev().collect::<Vec<_>>();
    println!("Found {} commits", commits.len());

    let data_file_path = flags.output.unwrap_or_else(|| PathBuf::from("data.json"));
    let data_file = OpenOptions::new()
        .append(true)
        .create(true)
        .open(data_file_path)?;
    let commit_len = commits.len();
    for (idx, commit) in commits.iter().enumerate() {
        let wall_clock_timestamp = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        println!("{}/{}: Checking out {commit}", idx + 1, commit_len);
        cmd!(sh, "git reset --hard {commit}").run()?;

        let timestamp = cmd!(sh, "git log --pretty=format:%ct -1 {commit}")
            .read()?
            .parse()?;

        let mut batch = MetricBatch {
            timestamp,
            metrics: vec![],
            attributes: Attributes {
                git_commit: commit.to_string(),
                wall_clock_timestamp,
            },
        };

        for recorder in metric_recorders {
            let name = recorder.name();
            if !enabled_metrics.is_empty() && !enabled_metrics.contains(&name) {
                continue;
            }

            match recorder.record(&sh) {
                Ok(metrics) => batch.metrics.extend(metrics),
                Err(e) => {
                    eprintln!(
                        "commit: {commit} - failed to run recorder {}, error: {:?}",
                        recorder.name(),
                        e
                    );
                }
            }
        }

        if !batch.metrics.is_empty() {
            writeln!(&data_file, "{}", serde_json::to_string(&batch)?)?;
            data_file.sync_all()?;
        }
    }

    Ok(())
}

fn merge(flags: flags::Run) -> Result<()> {
    let mut batch_ts = HashMap::new();
    let mut batches: Vec<MetricBatch> = vec![];

    for file in flags.files {
        let fp = fs::read_to_string(file)?;
        let lines = fp.lines();

        for line in lines {
            let batch: MetricBatch = serde_json::from_str(line)?;

            if let Some(&idx) = batch_ts.get(&batch.timestamp) {
                let existing_batch: &mut MetricBatch = &mut batches[idx];
                existing_batch.metrics.extend(batch.metrics);
            } else {
                batch_ts.insert(batch.timestamp, batches.len());
                batches.push(batch);
            }
        }
    }

    batches.sort_by_key(|e| e.timestamp);

    let data_file_path = flags.output.unwrap_or_else(|| PathBuf::from("data.json"));
    let data_file = File::create(data_file_path)?;

    for batch in batches {
        writeln!(&data_file, "{}", serde_json::to_string(&batch)?)?;
    }

    Ok(())
}

#[derive(Serialize, Deserialize)]
struct MetricBatch {
    timestamp: u64,
    metrics: Vec<Metric>,
    attributes: Attributes,
}

#[derive(Serialize, Deserialize)]
struct Attributes {
    git_commit: String,
    wall_clock_timestamp: u64,
}

#[derive(Serialize, Deserialize)]
struct Metric {
    name: String,
    unit: String,
    value: u64,
}
