use std::collections::HashMap;
use std::fs::{self, File};
use std::io::{Write, Error as IoError};
use std::time::{Instant, SystemTime};

use serde::{Serialize, Deserialize};
use xshell::{Shell, cmd};

type Result<T, E = Box<dyn std::error::Error>> = std::result::Result<T, E>;

mod flags {
    use std::path::PathBuf;

    xflags::xflags! {
        src "./src/main.rs"

        cmd run {
            /// The revset to pick. Passed on to `revset` to determine commits to examine.
            /// If unspecified, uses `HEAD^..HEAD` (only the latest commit).
            optional -r, --revset commit: String

            /// Repository URL to clone from
            required -u, --url url: String

            /// Repository path
            required -p, --path path: PathBuf
        }
    }
    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Run {
        pub revset: Option<String>,
        pub url: String,
        pub path: PathBuf,
    }

    impl Run {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}

fn main() -> Result<()> {
    let flags = match flags::Run::from_env() {
        Ok(flags) => flags,
        Err(err) => err.exit()
    };

     run(flags)
}

fn run(flags: flags::Run) -> Result<()> {
    let sh = Shell::new()?;

    let repo = flags.path;

    if repo.is_dir() {
        sh.change_dir(&repo);
        cmd!(sh, "git fetch origin").run()?;
    } else {
        let url = flags.url;
        cmd!(sh, "git clone {url} {repo} --branch main").run()?;
        sh.change_dir(&repo);
    }

    let revset = flags.revset.unwrap_or_else(|| String::from("HEAD^..HEAD"));
    let commits = cmd!(sh, "git rev-list {revset}").read()?;
    let commits = commits.lines().rev().collect::<Vec<_>>();
    println!("Found {} commits", commits.len());

    let data_file = File::create("data.json")?;
    let commit_len = commits.len();
    for (idx, commit) in commits.iter().enumerate() {
        let wall_clock_timestamp = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default().as_secs();

        println!("{}/{}: Checking out {commit}", idx+1, commit_len);
        cmd!(sh, "git reset --hard {commit}").run()?;

        let timestamp = cmd!(sh, "git log --pretty=format:%ct -1 {commit}").read()?.parse()?;

        let mut batch = MetricBatch {
            timestamp,
            metrics: vec![],
            attributes: Attributes { git_commit: commit.to_string(), wall_clock_timestamp }
        };

        if let Ok(metric) = android_build_size(&sh) {
            batch.metrics.push(metric);
        }

        if let Ok(metrics) = code_size(&sh) {
            batch.metrics.extend(metrics);
        }

        if let Ok(metric) = metric_count(&sh) {
            batch.metrics.push(metric);
        }

        writeln!(&data_file, "{}", serde_json::to_string(&batch)?)?;
        data_file.sync_all()?;
    }

    Ok(())
}

fn android_build_size(sh: &Shell) -> Result<Metric> {
    build_android(&sh)?;

    let lib_file = sh.current_dir().join("glean-core/android-native/build/rustJniLibs/android/arm64-v8a/libxul.so");
    let Ok(metadata) = lib_file.metadata() else { return Err(IoError::other("no metadata").into()) };
    if !metadata.is_file() {
        return Err(IoError::other("not a file").into());
    }

    let lib_size = metadata.len();
    Ok(Metric {
        name: String::from("lib size arm64-v8"),
        unit: String::from("bytes"),
        value: lib_size,
    })
}

type Tokei = HashMap<String, TokeiStats>;

#[derive(Deserialize)]
struct TokeiStats {
    code: u64,
}

fn code_size(sh: &Shell) -> Result<Vec<Metric>> {
    let tokei_out = cmd!(sh, "tokei -o json -e glean-core/android/build -t rust,kotlin,swift,python glean-core").read()?;
    let tokei_json: Tokei = serde_json::from_str(&tokei_out)?;

    let mut metrics = Vec::new();
    for (lang, stats) in tokei_json {
        let metric = Metric {
            name: format!("Lines of code - {lang}"),
            unit: String::from(""),
            value: stats.code,
        };
        metrics.push(metric);

    }

    Ok(metrics)
}

fn metric_count(sh: &Shell) -> Result<Metric> {
    let metric_count = cmd!(sh, "rg -c '^  [a-z]' glean-core/metrics.yaml").read()?.parse()?;
    let metric = Metric {
        name: format!("Number of built-in metrics"),
        unit: String::from(""),
        value: metric_count,
    };
    Ok(metric)
}

fn build_android(sh: &Shell) -> Result<()> {
    let _env = sh.push_env("CI", "1");
    let _env = sh.push_env("GRADLE_OPTS", "-Dorg.gradle.daemon=false");

    if fs::exists("local.properties").unwrap_or(false) {
        let dest = sh.current_dir().join("local.properties");
        fs::copy("local.properties", dest)?;
    }

    let now = Instant::now();
    cmd!(sh, "./gradlew --no-daemon :glean-native:cargoBuildArm64").run()?;
    let duration = now.elapsed();
    println!("Build took: {:?}", duration);

    Ok(())
}

#[derive(Serialize)]
struct MetricBatch {
    timestamp: u64,
    metrics: Vec<Metric>,
    attributes: Attributes,
}

#[derive(Serialize)]
struct Attributes {
    git_commit: String,
    wall_clock_timestamp: u64,
}

#[derive(Serialize)]
struct Metric {
    name: String,
    unit: String,
    value: u64,
}
