use std::fs::{self, File};
use std::io::Write;
use std::time::SystemTime;

use serde::Serialize;
use xshell::{Shell, cmd};

type Result<T, E = Box<dyn std::error::Error>> = std::result::Result<T, E>;

mod flags {
    use std::path::PathBuf;

    xflags::xflags! {
        src "./src/main.rs"

        cmd run {
            /// Start from this commit. Start of the repository if not specified.
            optional -s, --start commit: String
            /// Stop at this commit. `HEAD` of the repository if not specified. Note: This
            /// repository WILL be modified.
            optional -e, --end commit: String
            /// Repository URL to clone from
            required -u, --url url: String
            /// Repository path
            required -p, --path path: PathBuf
        }
    }
    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Run {
        pub start: Option<String>,
        pub end: Option<String>,
        pub url: String,
        pub path: PathBuf,
    }

    impl Run {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}

fn main() -> Result<()> {
    let flags = match flags::Run::from_env() {
        Ok(flags) => flags,
        Err(err) => err.exit()
    };

     run(flags)
}

fn run(flags: flags::Run) -> Result<()> {
    let sh = Shell::new()?;

    let repo = flags.path;

    if repo.is_dir() {
        sh.change_dir(&repo);
        cmd!(sh, "git fetch origin").run()?;
    } else {
        let url = flags.url;
        cmd!(sh, "git clone {url} {repo} --branch main").run()?;
        sh.change_dir(&repo);
    }

    let start = flags.start.unwrap_or_else(|| {
        let root_commit = cmd!(sh, "git rev-list --max-parents=0 HEAD").read().unwrap();
        println!("Starting from root commit: {root_commit}");
        root_commit
    });
    let end = flags.end.unwrap_or_else(|| String::from("origin/main"));
    let revset = format!("{start}..{end}");
    let commits = cmd!(sh, "git rev-list {revset}").read()?;
    let commits = commits.lines().rev().collect::<Vec<_>>();
    println!("Found {} commits", commits.len());

    let mut batches = Vec::new();

    let commit_len = commits.len();
    for (idx, commit) in commits.iter().enumerate() {
        let wall_clock_timestamp = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap_or_default().as_secs();

        println!("{}/{}: Checking out {commit}", idx+1, commit_len);
        cmd!(sh, "git reset --hard {commit}").run()?;


        build_android(&sh)?;

        let lib_file = repo.join("glean-core/android-native/build/rustJniLibs/android/arm64-v8a/libxul.so");
        let Ok(metadata) = lib_file.metadata() else { continue };
        if !metadata.is_file() {
            continue;
        }

        let timestamp = cmd!(sh, "git log --pretty=format:%ct -1 {commit}").read()?.parse()?;

        let mut batch = MetricBatch {
            timestamp,
            metrics: vec![],
            attributes: Attributes { git_commit: commit.to_string(), wall_clock_timestamp }
        };

        let lib_size = metadata.len();
        batch.metrics.push(Metric {
            name: String::from("lib size arm64-v8"),
            unit: String::from("bytes"),
            value: lib_size,
        });

        batches.push(batch);
    }

    let data_file = File::create("data.json")?;
    for batch in batches {
        writeln!(&data_file, "{}", serde_json::to_string(&batch)?)?;
    }

    Ok(())
}

fn build_android(sh: &Shell) -> Result<()> {
    let _env = sh.push_env("CI", "1");
    let _env = sh.push_env("GRADLE_OPTS", "-Dorg.gradle.daemon=false");

    if fs::exists("local.properties").unwrap_or(false) {
        fs::copy("local.properties", sh.current_dir())?;
    }

    cmd!(sh, "./gradlew --no-daemon :glean-native:cargoBuildArm64").run()?;

    Ok(())
}

#[derive(Serialize)]
struct MetricBatch {
    timestamp: u64,
    metrics: Vec<Metric>,
    attributes: Attributes,
}

#[derive(Serialize)]
struct Attributes {
    git_commit: String,
    wall_clock_timestamp: u64,
}

#[derive(Serialize)]
struct Metric {
    name: String,
    unit: String,
    value: u64,
}
